In [276]:
import pandas as pd
import numpy as np
import io

In [369]:
df = pd.read_csv('cars_engage_2022.csv')

In [284]:
df

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1272,1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1273,1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1274,1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1275,1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200 cc,4.0,4.0,AWD (All Wheel Drive),In-line,...,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [370]:
df["Make"].fillna("Unknown", inplace=True)
df["Displacement"]=df["Displacement"].str.rstrip("cc")
df["Displacement"]=pd.to_numeric(df["Displacement"],errors='coerce')
df["Displacement"].fillna(df["Displacement"].mean(),inplace=True)
df["Cylinders"].fillna(df["Cylinders"].mean(),inplace=True)
df["Valves_Per_Cylinder"].fillna(df["Valves_Per_Cylinder"].mean(),inplace=True)
df["Drivetrain"].fillna("Unknown", inplace=True)
df["Cylinder_Configuration"].fillna("Unknown", inplace=True)
df["Emission_Norm"].fillna("Unknown", inplace=True)
df["Engine_Location"].fillna("Unknown", inplace=True)
df["Fuel_System"].fillna("Unknown", inplace=True)
df["Fuel_Tank_Capacity"]=df["Fuel_Tank_Capacity"].str.rstrip("litres")
df["Fuel_Tank_Capacity"]=pd.to_numeric(df["Fuel_Tank_Capacity"],errors='coerce')
df["Fuel_Tank_Capacity"].fillna(df["Fuel_Tank_Capacity"].mean(),inplace=True)
df["Height"]=df["Height"].str.rstrip("mm")
df["Height"]=pd.to_numeric(df["Height"],errors='coerce')
df["Height"].fillna(df["Height"].mean(),inplace=True)
df["Width"]=df["Width"].str.rstrip("mm")
df["Width"]=pd.to_numeric(df["Width"],errors='coerce')
df["Width"].fillna(df["Width"].mean(),inplace=True)
df["Body_Type"].fillna("Unknown", inplace=True)
df["Doors"].fillna(df["Doors"].mean(),inplace=True)
df["City_Mileage"]=df["City_Mileage"].str.replace("?","")
df["City_Mileage"]=df["City_Mileage"].str.replace(",",".")
df["City_Mileage"]=df["City_Mileage"].str.rstrip("km/litre")
df["City_Mileage"]=pd.to_numeric(df["City_Mileage"],errors='coerce')
df["City_Mileage"].fillna(df["City_Mileage"].mean(),inplace=True)
df["Highway_Mileage"]=df["Highway_Mileage"].str.replace("?","")
df["Highway_Mileage"]=df["Highway_Mileage"].str.replace(",",".")
df["Highway_Mileage"]=df["Highway_Mileage"].str.rstrip("km/litre")
df["Highway_Mileage"]=pd.to_numeric(df["Highway_Mileage"],errors='coerce')
df["Highway_Mileage"].fillna(df["Highway_Mileage"].mean(),inplace=True)
df["ARAI_Certified_Mileage"]=df["ARAI_Certified_Mileage"].str.replace("?","")
df["ARAI_Certified_Mileage"]=df["ARAI_Certified_Mileage"].str.replace(",",".")
df["ARAI_Certified_Mileage"]=df["ARAI_Certified_Mileage"].str.rstrip("km/litre")
df["ARAI_Certified_Mileage"]=pd.to_numeric(df["ARAI_Certified_Mileage"],errors='coerce')
df["ARAI_Certified_Mileage"].fillna(df["ARAI_Certified_Mileage"].mean(),inplace=True)
df["ARAI_Certified_Mileage_for_CNG"].fillna((df["ARAI_Certified_Mileage_for_CNG"].str.rstrip("km/kg").astype(float)).mean(),inplace=True)
df["Kerb_Weight"]=df["Kerb_Weight"].str.rstrip("kg")
df["Kerb_Weight"]=pd.to_numeric(df["Kerb_Weight"],errors='coerce')
df["Kerb_Weight"].fillna(df["Kerb_Weight"].mean(),inplace=True)
df["Gears"]=pd.to_numeric(df["Gears"],errors='coerce')
df["Gears"].fillna(df["Gears"].mean(),inplace=True)
df["Ground_Clearance"].fillna((df["Ground_Clearance"].str.rstrip("mm").astype(float)).mean(),inplace=True)
df["Front_Brakes"].fillna("Front_Brakes", inplace=True)
df["Rear_Brakes"].fillna("Rear_Brakes", inplace=True)
df["Front_Suspension"].fillna("Front_Suspension", inplace=True)
df["Rear_Suspension"].fillna("Rear_Suspension", inplace=True)
df["Front_Track"]=df["Front_Track"].str.rstrip("mm")
df["Front_Track"]=pd.to_numeric(df["Front_Track"],errors='coerce')
df["Front_Track"].fillna(df["Front_Track"].mean(),inplace=True)
df["Rear_Track"]=df["Rear_Track"].str.rstrip("mm")
df["Rear_Track"]=pd.to_numeric(df["Rear_Track"],errors='coerce')
df["Rear_Track"].fillna(df["Rear_Track"].mean(),inplace=True)
df["Front_Tyre_&_Rim"].fillna("Unknown", inplace=True)
df["Rear_Tyre_&_Rim"].fillna("Unknown", inplace=True)
df["Power_Steering"].fillna("Unknown", inplace=True)
df["Power_Windows"].fillna("Unknown", inplace=True)
df["Power_Seats"].fillna("Unknown", inplace=True)
df["Keyless_Entry"].fillna("Unknown", inplace=True)
df["Torque"].fillna("Unknown", inplace=True)
df["Odometer"].fillna("Unknown", inplace=True)
df["Speedometer"].fillna("Unknown", inplace=True)
df["Tachometer"].fillna("Unknown", inplace=True)
df["Tripmeter"].fillna("Unknown", inplace=True)
df["Seating_Capacity"]=pd.to_numeric(df["Seating_Capacity"],errors='coerce')
df["Seating_Capacity"].fillna(df["Seating_Capacity"].mean(),inplace=True)
df["Seats_Material"].fillna("Unknown", inplace=True)
df["Type"].fillna("Unknown", inplace=True)
df["Wheelbase"].fillna("Unknown", inplace=True)
df["Wheels_Size"].fillna("Unknown", inplace=True)
df["Start_/_Stop_Button"].fillna("Unknown", inplace=True)
df["12v_Power_Outlet"].fillna("Unknown", inplace=True)
df["Audiosystem"].fillna("Unknown", inplace=True)
df["Aux-in_Compatibility"].fillna("Unknown", inplace=True)
df["Average_Fuel_Consumption"].fillna("Unknown", inplace=True)
df["Basic_Warranty"].fillna("Unknown", inplace=True)
df["Bluetooth"].fillna("Unknown", inplace=True)
df["Boot-lid_Opener"].fillna("Unknown", inplace=True)
df["Boot_Space"]=df["Boot_Space"].str.rstrip("litres")
df["Boot_Space"]=pd.to_numeric(df["Boot_Space"],errors='coerce')
df["Boot_Space"].fillna(df["Boot_Space"].mean(),inplace=True)
df["CD_/_MP3_/_DVD_Player"].fillna("Unknown", inplace=True)
df["Central_Locking"].fillna("Unknown", inplace=True)
df["Child_Safety_Locks"].fillna("Unknown", inplace=True)
df["Clock"].fillna("Unknown", inplace=True)
df["Cup_Holders"].fillna("Unknown", inplace=True)
df["Distance_to_Empty"].fillna("Unknown", inplace=True)
df["Door_Pockets"].fillna("Unknown", inplace=True)
df["Engine_Malfunction_Light"].fillna("Unknown", inplace=True)
df["Extended_Warranty"].fillna("Unknown", inplace=True)
df["FM_Radio"].fillna("Unknown", inplace=True)
df["Fuel-lid_Opener"].fillna("Unknown", inplace=True)
df["Fuel_Gauge"].fillna("Unknown", inplace=True)
df["Handbrake"].fillna("Unknown", inplace=True)
df["Instrument_Console"].fillna("Unknown", inplace=True)
df["Low_Fuel_Warning"].fillna("Unknown", inplace=True)
df["Minimum_Turning_Radius"]=df["Minimum_Turning_Radius"].str.rstrip("meter")
df["Minimum_Turning_Radius"]=pd.to_numeric(df["Minimum_Turning_Radius"],errors='coerce')
df["Minimum_Turning_Radius"].fillna(df["Minimum_Turning_Radius"].mean(),inplace=True)
df["Multifunction_Display"].fillna("Unknown", inplace=True)
df["Sun_Visor"].fillna("Unknown", inplace=True)
df["Third_Row_AC_Vents"].fillna("Unknown", inplace=True)
df["Ventilation_System"].fillna("Unknown", inplace=True)
df["Auto-Dimming_Rear-View_Mirror"].fillna("Unknown", inplace=True)
df["Hill_Assist"].fillna("Unknown", inplace=True)
df["Gear_Indicator"].fillna("Unknown", inplace=True)
df["3_Point_Seat-Belt_in_Middle_Rear_Seat"].fillna("Unknown", inplace=True)
df["Ambient_Lightning"].fillna("Unknown", inplace=True)
df["Cargo/Boot_Lights"].fillna("Unknown", inplace=True)
df["Drive_Modes"].fillna("Unknown", inplace=True)
df["Engine_Immobilizer"].fillna("Unknown", inplace=True)
df["High_Speed_Alert_System"].fillna("Unknown", inplace=True)
df["Lane_Watch_Camera/_Side_Mirror_Camera"].fillna("Unknown", inplace=True)
df["Passenger_Side_Seat-Belt_Reminder"].fillna("Unknown", inplace=True)
df["Seat_Back_Pockets"].fillna("Unknown", inplace=True)
df["Voice_Recognition"].fillna("Unknown", inplace=True)
df["Walk_Away_Auto_Car_Lock"].fillna("Unknown", inplace=True)
df["ABS_(Anti-lock_Braking_System)"].fillna("Unknown", inplace=True)
df["Headlight_Reminder"].fillna("Unknown", inplace=True)
df["Adjustable_Headrests"].fillna("Unknown", inplace=True)
df["Gross_Vehicle_Weight"]=df["Gross_Vehicle_Weight"].str.rstrip("kg")
df["Gross_Vehicle_Weight"]=pd.to_numeric(df["Gross_Vehicle_Weight"],errors='coerce')
df["Gross_Vehicle_Weight"].fillna(df["Gross_Vehicle_Weight"].mean(),inplace=True)
df["Airbags"].fillna("Unknown", inplace=True)
df["Door_Ajar_Warning"].fillna("Unknown", inplace=True)
df["EBD_(Electronic_Brake-force_Distribution)"].fillna("Unknown", inplace=True)
df["Fasten_Seat_Belt_Warning"].fillna("Unknown", inplace=True)
df["Gear_Shift_Reminder"].fillna("Unknown", inplace=True)
df["Number_of_Airbags"]=pd.to_numeric(df["Number_of_Airbags"],errors='coerce')
df["Number_of_Airbags"].fillna(df["Number_of_Airbags"].mean(),inplace=True)
df["Compression_Ratio"]=pd.to_numeric(df["Compression_Ratio"],errors='coerce')
df["Compression_Ratio"].fillna(df["Compression_Ratio"].mean(),inplace=True)
df["Adjustable_Steering_Column"].fillna("Unknown", inplace=True)
df["Airbags"].fillna("Unknown", inplace=True)
df["Other_Specs"]=df["Other_Specs"].str.replace("NA","")
df["Other_Specs"].fillna("Unknown", inplace=True)
df["Other_specs"]=df["Other_specs"].str.replace("NA","")
df["Other_specs"].fillna("Unknown", inplace=True)
df["Parking_Assistance"].fillna("Unknown", inplace=True)
df["Key_Off_Reminder"].fillna("Unknown", inplace=True)
df["USB_Compatibility"].fillna("Unknown", inplace=True)
df["Android_Auto"].fillna("Unknown", inplace=True)
df["Apple_CarPlay"].fillna("Unknown", inplace=True)
df["Cigarette_Lighter"].fillna("Unknown", inplace=True)
df["Infotainment_Screen"].fillna("Unknown", inplace=True)
df["Multifunction_Steering_Wheel"].fillna("Unknown", inplace=True)
df["Average_Speed"].fillna("Unknown", inplace=True)
df["EBA_(Electronic_Brake_Assist)"].fillna("Unknown", inplace=True)
df["Seat_Height_Adjustment"].fillna("Unknown", inplace=True)
df["Navigation_System"].fillna("Unknown", inplace=True)
df["Second_Row_AC_Vents"].fillna("Unknown", inplace=True)
df["Tyre_Pressure_Monitoring_System"].fillna("Unknown", inplace=True)
df["Rear_Center_Armrest"].fillna("Unknown", inplace=True)
df["iPod_Compatibility"].fillna("Unknown", inplace=True)
df["ESP_(Electronic_Stability_Program)"].fillna("Unknown", inplace=True)
df["Cooled_Glove_Box"].fillna("Unknown", inplace=True)
df["Recommended_Tyre_Pressure"].fillna("Unknown", inplace=True)
df["Heated_Seats"].fillna("Unknown", inplace=True)
df["Turbocharger"].fillna("Unknown", inplace=True)
df["ISOFIX_(Child-Seat_Mount)"].fillna("Unknown", inplace=True)
df["Rain_Sensing_Wipers"].fillna("Unknown", inplace=True)
df["Paddle_Shifters"].fillna("Unknown", inplace=True)
df["Leather_Wrapped_Steering"].fillna("Unknown", inplace=True)
df["Automatic_Headlamps"].fillna("Unknown", inplace=True)
df["Engine_Type"].fillna("Unknown", inplace=True)
df["ASR_/_Traction_Control"].fillna("Unknown", inplace=True)
df["Cruise_Control"].fillna("Unknown", inplace=True)
df["USB_Ports"]=pd.to_numeric(df["USB_Ports"],errors='coerce')
df["USB_Ports"].fillna(df["USB_Ports"].mean(),inplace=True)
df["Heads-Up_Display"].fillna("Unknown", inplace=True)
df["Welcome_Lights"].fillna("Unknown", inplace=True)
df["Battery"].fillna("Unknown", inplace=True)
df["Electric_Range"]=df["Electric_Range"].str.rstrip("km/full charge")
df["Electric_Range"]=pd.to_numeric(df["Electric_Range"],errors='coerce')
df["Electric_Range"].fillna(df["Electric_Range"].mean(),inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [367]:
(df.isnull().sum()).sum()

0

In [368]:
df

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624.0,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Unknown,1.793103,Unknown,Unknown,Unknown,195.17
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624.0,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Unknown,1.793103,Unknown,Unknown,Unknown,195.17
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624.0,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Unknown,1.793103,Unknown,Unknown,Unknown,195.17
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624.0,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Unknown,1.793103,Unknown,Unknown,Unknown,195.17
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624.0,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Unknown,1.793103,Unknown,Unknown,Unknown,195.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498.0,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Unknown,Unknown,Unknown,Yes,1.793103,Unknown,Unknown,Unknown,195.17
1272,1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498.0,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,Unknown,Unknown,Yes,1.793103,Unknown,Unknown,Unknown,195.17
1273,1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Yes,Yes,Unknown,Unknown,Yes,1.793103,Unknown,Unknown,Unknown,195.17
1274,1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,...,Unknown,Unknown,Unknown,Unknown,Yes,1.793103,Unknown,Unknown,Unknown,195.17
1275,1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200.0,4.0,4.0,AWD (All Wheel Drive),In-line,...,Yes,Unknown,Unknown,Yes,Yes,1.793103,Unknown,Unknown,Unknown,195.17